name: update_kumu_and_shiny_data

# Controls when the workflow will run
on:
  schedule:
    - cron: "00 04 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GSHEET_ACCESS_PASSWORD: ${{ secrets.GSHEET_ACCESS_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install linux libraries
        run: sudo apt install libcurl4-openssl-dev libssl-dev libgdal-dev libsodium-dev

      - name: Setup R Dependencies (using renv.lock)
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
          
      - name: Run-r-script
        run: | 
          Rscript -e "source('scripts/data_for_kumu.R')"
          Rscript -e "source('scripts/data_for_shiny.R')"
       
      - name: Commit RData file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update Rdata file
          

